version: '3'

services:
  gridchaindnode0:
    container_name: gridchaindnode0
    image: "gridchain/node"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-gridchaind.log}
    volumes:
      - ./build:/gridchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  gridchaindnode1:
    container_name: gridchaindnode1
    image: "gridchain/node"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-gridchaind.log}
    volumes:
      - ./build:/gridchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  gridchaindnode2:
    container_name: gridchaindnode2
    image: "gridchain/node"
    environment:
      - ID=2
      - LOG=${LOG:-gridchaind.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/gridchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  gridchaindnode3:
    container_name: gridchaindnode3
    image: "gridchain/node"
    environment:
      - ID=3
      - LOG=${LOG:-gridchaind.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/gridchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

